---
name: Docker Image CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ros2:$(date +%s)
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Docker Image
        run: docker build -t ros2:$(date +%s) .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWORD }}
